server:
  port: 8083

spring:
  h2:
    console:
      enabled: true

jwt:
  secret: secretkey123

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    instance:
#      hostname: localhost

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8083/eureka
    instance:
      hostname: localhost